# Generated by Django 4.1.6 on 2023-02-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288)),
                ('email', models.CharField(max_length=288)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
